# Generated by Django 5.2.13 on 2026-06-07 07:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المركز')),
            ],
            options={
                'verbose_name': 'مركز',
                'verbose_name_plural': 'المراكز',
            },
        ),
        migrations.CreateModel(
            name='CenterEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم معدة المركز')),
            ],
            options={
                'verbose_name': 'معدات المركز',
                'verbose_name_plural': 'معدات المراكز',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السائق')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('residence', models.CharField(max_length=200, verbose_name='مكان السكن')),
                ('city_or_village', models.CharField(max_length=100, verbose_name='المدينة / القرية')),
                ('license_info', models.CharField(max_length=200, verbose_name='معلومات رخصة القيادة')),
                ('work_location', models.CharField(max_length=200, verbose_name='موقع العمل')),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='drivers/id_cards/', verbose_name='صورة الهوية')),
                ('personal_image', models.ImageField(blank=True, null=True, upload_to='drivers/photos/', verbose_name='صورة شخصية')),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='drivers/licenses/', verbose_name='صورة الرخصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقين',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموظف')),
                ('mobile', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('address', models.CharField(max_length=200, verbose_name='مكان السكن')),
                ('rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='رتبة الموظف')),
                ('rank_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الرتبة')),
                ('education_level', models.CharField(blank=True, max_length=200, null=True, verbose_name='المستوى العلمي')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='الوصف الوظيفي')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
            },
        ),
        migrations.CreateModel(
            name='FuelQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now, verbose_name='الشهر')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المخصص (شيكل)')),
                ('allocated_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المخصصة (لتر)')),
            ],
            options={
                'verbose_name': 'مخصص وقود',
                'verbose_name_plural': 'مخصصات الوقود',
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المحافظة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('color', models.CharField(default='blue', max_length=10, verbose_name='اللون')),
            ],
            options={
                'verbose_name': 'سجل موقع',
                'verbose_name_plural': 'سجلات المواقع',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_number', models.CharField(editable=False, max_length=6, unique=True, verbose_name='رقم الصيانة')),
                ('garage', models.CharField(max_length=200, verbose_name='اسم الكراج')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الصيانة')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الفاتورة')),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='invoices/', verbose_name='صورة الفاتورة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التكلفة الإجمالية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'صيانة',
                'verbose_name_plural': 'الصيانة',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='العنوان / البحث')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البحث')),
            ],
            options={
                'verbose_name': 'بحث',
                'verbose_name_plural': 'عمليات البحث',
            },
        ),
        migrations.CreateModel(
            name='StoreEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم معدة المخزن')),
            ],
            options={
                'verbose_name': 'معدات المخزن',
                'verbose_name_plural': 'معدات المخازن',
            },
        ),
        migrations.CreateModel(
            name='VehiclesEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المعدات')),
            ],
            options={
                'verbose_name': 'معدات المركبة',
                'verbose_name_plural': 'معدات المركبات',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.center')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.governorate')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_governorate', models.CharField(default='غير محددة', max_length=100, verbose_name='محافظة الكارثة')),
                ('owner_name', models.CharField(max_length=100, verbose_name='اسم المالك')),
                ('building_name', models.CharField(max_length=100, verbose_name='اسم المبنى')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('floors', models.IntegerField(verbose_name='عدد الطوابق')),
                ('has_parking', models.BooleanField(verbose_name='يوجد موقف سيارات')),
                ('latitude', models.FloatField(default=0.0, verbose_name='خط العرض')),
                ('longitude', models.FloatField(default=0.0, verbose_name='خط الطول')),
                ('address', models.TextField(default='بدون عنوان', verbose_name='العنوان')),
                ('evaluated', models.BooleanField(default=False, verbose_name='تم التقييم')),
                ('evaluation', models.CharField(blank=True, choices=[('A', 'تقييم A'), ('B', 'تقييم B'), ('C', 'تقييم C')], max_length=1, null=True, verbose_name='التقييم')),
                ('status', models.CharField(default='لم يتم التقييم', max_length=100, verbose_name='الحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.center', verbose_name='المركز')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'المباني',
            },
        ),
        migrations.CreateModel(
            name='BuildingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='disaster_images/', verbose_name='صورة')),
                ('video', models.FileField(blank=True, null=True, upload_to='disaster_videos/', verbose_name='فيديو')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='map.buildinginfo', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'وسائط مبنى',
                'verbose_name_plural': 'وسائط المباني',
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ المغادرة')),
                ('reason', models.TextField(verbose_name='سبب المغادرة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='map.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مغادرة',
                'verbose_name_plural': 'المغادرات',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشهادة / الدورة')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحصول عليها')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='ملف الشهادة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='map.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات والدورات',
            },
        ),
        migrations.CreateModel(
            name='FuelFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التعبئة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية (لتر)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ (شيكل)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='fuel_receipts/', verbose_name='صورة الوصل')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.driver', verbose_name='السائق')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillings', to='map.fuelquota', verbose_name='المخصص الشهري')),
            ],
            options={
                'verbose_name': 'تعبئة وقود',
                'verbose_name_plural': 'تعبئات الوقود',
            },
        ),
        migrations.AddField(
            model_name='center',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='map.governorate', verbose_name='المحافظة'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الحادث')),
                ('description', models.TextField(verbose_name='وصف الحادث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.center', verbose_name='المركز')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.department', verbose_name='القسم')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'حادث',
                'verbose_name_plural': 'الحوادث',
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحادث')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='وقت الحادث')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الكشف')),
                ('inspection_time', models.TimeField(blank=True, null=True, verbose_name='وقت الكشف')),
                ('end_inspection_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الكشف')),
                ('end_inspection_time', models.TimeField(blank=True, null=True, verbose_name='وقت انتهاء الكشف')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المالك')),
                ('occupation_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المهنة')),
                ('insured_status', models.CharField(blank=True, choices=[('insured', 'مؤمن'), ('uninsured', 'غير مؤمن')], max_length=100, null=True, verbose_name='حالة التأمين')),
                ('general_description', models.TextField(blank=True, null=True, verbose_name='وصف عام')),
                ('technical_observations', models.TextField(blank=True, null=True, verbose_name='ملاحظات فنية')),
                ('fire_start_area', models.TextField(blank=True, null=True, verbose_name='منطقة بداية الحريق')),
                ('damages', models.TextField(blank=True, null=True, verbose_name='الأضرار')),
                ('cause_of_incident', models.TextField(blank=True, null=True, verbose_name='سبب الحادث')),
                ('technical_analysis', models.TextField(blank=True, null=True, verbose_name='التحليل الفني')),
                ('committee_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='توقيع اللجنة')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('current_address', models.TextField(blank=True, null=True, verbose_name='العنوان الحالي')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='investigations/signatures/', verbose_name='صورة التوقيع')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.center', verbose_name='المركز')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.governorate', verbose_name='المحافظة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحقيق',
                'verbose_name_plural': 'التحقيقات',
            },
        ),
        migrations.CreateModel(
            name='InvestigationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='investigations/images/', verbose_name='صورة')),
                ('video', models.FileField(blank=True, null=True, upload_to='investigations/videos/', verbose_name='فيديو')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='map.investigation', verbose_name='التحقيق')),
            ],
            options={
                'verbose_name': 'وسائط تحقيق',
                'verbose_name_plural': 'وسائط التحقيقات',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='map.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ العطل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance/items/', verbose_name='صورة العطل')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='map.maintenance', verbose_name='الصيانة')),
            ],
            options={
                'verbose_name': 'عنصر صيانة',
                'verbose_name_plural': 'عناصر الصيانة',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('objective', models.TextField(blank=True, null=True, verbose_name='الهدف')),
                ('services', models.TextField(blank=True, null=True, verbose_name='الخدمات')),
                ('landline', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف الأرضي')),
                ('emergency_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الطوارئ')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف الخلوي')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.center', verbose_name='المركز')),
                ('center_equipment', models.ManyToManyField(blank=True, to='map.centerequipment', verbose_name='معدات المركز')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.governorate', verbose_name='المحافظة')),
                ('store_equipment', models.ManyToManyField(blank=True, to='map.storeequipment', verbose_name='معدات المخزن')),
                ('vehicle_equipment', models.ManyToManyField(blank=True, to='map.vehiclesequipment', verbose_name='معدات المركبة')),
            ],
            options={
                'verbose_name': 'مركز العمليات',
                'verbose_name_plural': 'مراكز العمليات',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='map.operation', verbose_name='المركز'),
        ),
        migrations.CreateModel(
            name='OperationCenterEquipmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='equipment_files/center/', verbose_name='ملف معدات مركز')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='وصف الملف')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_files', to='map.operation')),
            ],
            options={
                'verbose_name': 'ملف معدات مركز مرفق',
            },
        ),
        migrations.CreateModel(
            name='OperationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='operation_images/', verbose_name='صورة')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='وصف الصورة')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_images', to='map.operation')),
            ],
            options={
                'verbose_name': 'صورة المركز',
            },
        ),
        migrations.CreateModel(
            name='OperationStoreEquipmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='equipment_files/store/', verbose_name='ملف معدات مخزن')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='وصف الملف')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_files', to='map.operation')),
            ],
            options={
                'verbose_name': 'ملف معدات مخزن مرفق',
            },
        ),
        migrations.CreateModel(
            name='OperationVehicleEquipmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='equipment_files/vehicle/', verbose_name='ملف معدات مركبة')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='وصف الملف')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_files', to='map.operation')),
            ],
            options={
                'verbose_name': 'ملف معدات مركبة مرفق',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('hq', 'الإدارة العامة'), ('dept', 'إدارة'), ('gov', 'محافظة'), ('center', 'مركز'), ('sector', 'قاطع'), ('support_center', 'مركز إسناد')], db_index=True, max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='map.organizationunit')),
            ],
            options={
                'verbose_name': 'وحدة تنظيمية',
                'verbose_name_plural': 'الوحدات التنظيمية',
            },
        ),
        migrations.CreateModel(
            name='OvernightShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='بداية الشيفت')),
                ('end_datetime', models.DateTimeField(verbose_name='نهاية الشيفت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overnight_shifts', to='map.employee', verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='PublicSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المالك')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='واتساب')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المنشأة')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة')),
                ('map_address', models.TextField(blank=True, null=True, verbose_name='عنوان الخريطة')),
                ('manual_address', models.TextField(blank=True, null=True, verbose_name='عنوان يدوي')),
                ('is_ready', models.BooleanField(default=False, verbose_name='جاهز')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المساحة')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإيصال')),
                ('required_actions', models.TextField(blank=True, null=True, verbose_name='الإجراءات المطلوبة')),
                ('actions_done', models.TextField(blank=True, null=True, verbose_name='الإجراءات المنفذة')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.center', verbose_name='المركز')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.governorate', verbose_name='المحافظة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'السلامة العامة',
                'verbose_name_plural': 'السلامة العامة',
            },
        ),
        migrations.CreateModel(
            name='PublicSafetyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public_safety/images/', verbose_name='صورة')),
                ('video', models.FileField(blank=True, null=True, upload_to='public_safety/videos/', verbose_name='فيديو')),
                ('public_safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='map.publicsafety', verbose_name='السلامة العامة')),
            ],
            options={
                'verbose_name': 'ملف سلامة عامة',
                'verbose_name_plural': 'ملفات السلامة العامة',
            },
        ),
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public_safety/receipts/', verbose_name='صورة الإيصال')),
                ('public_safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_images', to='map.publicsafety', verbose_name='السلامة العامة')),
            ],
            options={
                'verbose_name': 'إيصال',
                'verbose_name_plural': 'الإيصالات',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocumentsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public_safety/documents/', verbose_name='الوثيقة')),
                ('public_safety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_docs_images', to='map.publicsafety', verbose_name='السلامة العامة')),
            ],
            options={
                'verbose_name': 'وثيقة مطلوبة',
                'verbose_name_plural': 'الوثائق المطلوبة',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.PositiveIntegerField(db_index=True, default=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_roles', to='map.role')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.role')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.organizationunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تعيين وظيفي',
                'verbose_name_plural': 'التعيينات الوظيفية',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المركبة')),
                ('work_type', models.CharField(choices=[('fire', 'إطفاء'), ('rescue', 'إنقاذ'), ('services', 'خدمات'), ('tank', 'تنك تزويد')], max_length=20, verbose_name='نوع المهمة')),
                ('vehicle_type', models.CharField(max_length=100, verbose_name='نوع المركبة')),
                ('model', models.CharField(max_length=100, verbose_name='الطراز')),
                ('category', models.CharField(max_length=100, verbose_name='الصنف')),
                ('fuel_type', models.CharField(choices=[('diesel', 'ديزل'), ('petrol', 'بنزين')], max_length=20, verbose_name='نوع الوقود')),
                ('engine_power', models.CharField(max_length=50, verbose_name='قدرة المحرك')),
                ('chassis_number', models.CharField(max_length=100, verbose_name='رقم الشصي')),
                ('status', models.CharField(choices=[('in_service', 'داخل الخدمة'), ('out_service', 'خارج الخدمة')], default='in_service', max_length=20, verbose_name='الحالة')),
                ('status_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الحالة')),
                ('production_year', models.PositiveIntegerField(verbose_name='سنة الإنتاج')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='نهاية التأمين')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='نهاية الترخيص')),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='شركة التأمين')),
                ('insurance_image', models.ImageField(blank=True, null=True, upload_to='vehicles/insurance/', verbose_name='صورة التأمين')),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='vehicles/license/', verbose_name='صورة الترخيص')),
                ('work_nature', models.CharField(blank=True, max_length=200, null=True, verbose_name='طبيعة العمل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.center', verbose_name='المركز')),
                ('drivers', models.ManyToManyField(blank=True, related_name='vehicles', to='map.driver', verbose_name='السائقين')),
                ('governorate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200, verbose_name='الوجهة')),
                ('start_odometer', models.PositiveIntegerField(verbose_name='عداد البداية')),
                ('start_odometer_image', models.ImageField(blank=True, null=True, upload_to='odometer/start/')),
                ('end_odometer', models.PositiveIntegerField(verbose_name='عداد النهاية')),
                ('end_odometer_image', models.ImageField(blank=True, null=True, upload_to='odometer/end/')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الرحلة')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='map.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='map.vehicle', verbose_name='المركبة'),
        ),
        migrations.AddField(
            model_name='fuelquota',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_quotas', to='map.vehicle', verbose_name='المركبة'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='الصورة')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'صورة مركبة',
                'verbose_name_plural': 'صور المركبات',
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_service', 'داخل الخدمة'), ('out_service', 'خارج الخدمة')], max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التغيير')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='map.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'تاريخ حالة المركبة',
                'verbose_name_plural': 'تاريخ حالات المركبات',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'الاثنين'), ('tue', 'الثلاثاء'), ('wed', 'الأربعاء'), ('thu', 'الخميس'), ('fri', 'الجمعة'), ('sat', 'السبت'), ('sun', 'الأحد')], max_length=10, verbose_name='اليوم')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('is_night_shift', models.BooleanField(default=False, verbose_name='شيفت ليلي')),
                ('is_off', models.BooleanField(default=False, verbose_name='يوم عطلة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='map.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'جدول دوام',
                'verbose_name_plural': 'جداول الدوام',
            },
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['unit_type', 'parent'], name='map_organiz_unit_ty_65549f_idx'),
        ),
        migrations.AddIndex(
            model_name='userassignment',
            index=models.Index(fields=['user', 'unit'], name='map_userass_user_id_282861_idx'),
        ),
        migrations.AddIndex(
            model_name='userassignment',
            index=models.Index(fields=['role', 'unit'], name='map_userass_role_id_958ea9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'day')},
        ),
    ]
