# Generated by Django 5.2.13 on 2026-06-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_customuser_options_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
    ]
