# Generated by Django 5.2.13 on 2026-06-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'محافظة', 'verbose_name_plural': '1-لمحافظات'},
        ),
    ]
