# Generated by Django 5.2.13 on 2026-06-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_governorate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون-4'},
        ),
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'verbose_name': 'وحدة تنظيمية', 'verbose_name_plural': 'الوحدات التنظيمية-3'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level'], 'verbose_name': 'دور', 'verbose_name_plural': '2-الأدوار'},
        ),
        migrations.AlterModelOptions(
            name='userassignment',
            options={'verbose_name': 'تعيين وظيفي', 'verbose_name_plural': 'التعيينات الوظيفية-5'},
        ),
    ]
