# Generated by Django 5.2.13 on 2026-06-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون -4'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'محافظة', 'verbose_name_plural': '1- لمحافظات'},
        ),
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'verbose_name': 'وحدة تنظيمية', 'verbose_name_plural': 'الوحدات التنظيمية -3'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level'], 'verbose_name': 'دور', 'verbose_name_plural': '2- الأدوار'},
        ),
        migrations.AlterModelOptions(
            name='userassignment',
            options={'verbose_name': 'تعيين وظيفي', 'verbose_name_plural': 'التعيينات الوظيفية -5'},
        ),
    ]
