# Generated by Django 5.2.13 on 2026-06-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('map', '0006_alter_customuser_options_alter_governorate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='الصلاحيات الممنوحة'),
        ),
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=100, verbose_name='المستوى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الدور/الرتبة'),
        ),
        migrations.AlterField(
            model_name='role',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_roles', to='map.role', verbose_name='الدور الأعلى'),
        ),
    ]
