# Generated by Django 5.2.13 on 2026-06-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_role_permissions_alter_role_level_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level'], 'permissions': [('can_view_operations_map', 'قادر على عرض خريطة العمليات والاستعلام عنها')], 'verbose_name': 'دور', 'verbose_name_plural': '2- الأدوار'},
        ),
    ]
