# Generated by Django 5.2.13 on 2026-06-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_role_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organizationunit',
            name='map_organiz_unit_ty_65549f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userassignment',
            name='map_userass_user_id_282861_idx',
        ),
        migrations.RemoveIndex(
            model_name='userassignment',
            name='map_userass_role_id_958ea9_idx',
        ),
        migrations.AddField(
            model_name='userassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.department', verbose_name='القسم / الإدارة المختصة'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الوحدة التنظيمية'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='map.organizationunit', verbose_name='التبعية المباشرة'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('hq', 'الإدارة العامة / المديرية العامة'), ('dept', 'إدارة عامة مختصة / مساندة'), ('sector', 'قاطع جغرافي (شمال/وسط/جنوب)'), ('support_center_hq', 'قيادة مراكز الإسناد'), ('gov', 'مديرية محافظة'), ('center', 'مركز إطفاء وإنقاذ'), ('support_center', 'مركز إسناد فرعي')], db_index=True, max_length=30, verbose_name='نوع الوحدة'),
        ),
    ]
