# Generated by Django 5.2.13 on 2026-06-08 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_remove_organizationunit_map_organiz_unit_ty_65549f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='map.organizationunit'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('hq', 'الإدارة العامة'), ('dept', 'إدارة'), ('gov', 'محافظة'), ('center', 'مركز'), ('sector', 'قاطع'), ('support_center', 'مركز إسناد')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['unit_type', 'parent'], name='map_organiz_unit_ty_65549f_idx'),
        ),
    ]
