# Generated by Django 5.2.13 on 2026-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_organizationunit_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level'], 'verbose_name': 'دور', 'verbose_name_plural': '2- الأدوار'},
        ),
        migrations.RemoveField(
            model_name='userassignment',
            name='department',
        ),
        migrations.AddIndex(
            model_name='userassignment',
            index=models.Index(fields=['user', 'unit'], name='map_userass_user_id_282861_idx'),
        ),
        migrations.AddIndex(
            model_name='userassignment',
            index=models.Index(fields=['role', 'unit'], name='map_userass_role_id_958ea9_idx'),
        ),
    ]
