# Generated by Django 5.2.13 on 2026-06-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_role_options_remove_userassignment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassignment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.organizationunit', verbose_name='الوحدة التنظيمية الحالية'),
        ),
    ]
