# Generated by Django 5.2.13 on 2026-06-14 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_userassignment_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'مركز/مديرية', 'verbose_name_plural': 'المراكز والمديريات'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'محافظة', 'verbose_name_plural': '1- المحافظات'},
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='linked_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.center', verbose_name='المركز/المديرية المرتبطة'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='linked_governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.governorate', verbose_name='المحافظة المرتبطة'),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المركز / المديرية'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الوحدة'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='map.organizationunit', verbose_name='الوحدة الأعلى'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('hq', 'الإدارة العامة'), ('sector', 'قاطع'), ('gov', 'محافظة'), ('directorate', 'مديرية محافظة'), ('dept_branch', 'إدارة داخل مديرية'), ('center', 'مركز لهدف معين'), ('support_center', 'مركز إسناد')], db_index=True, max_length=30, verbose_name='نوع الوحدة'),
        ),
    ]
