# Generated by Django 5.2.13 on 2026-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_center_options_alter_governorate_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organizationunit',
            name='map_organiz_unit_ty_65549f_idx',
        ),
        migrations.RemoveField(
            model_name='organizationunit',
            name='parent',
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['unit_type'], name='map_organiz_unit_ty_ca0bb9_idx'),
        ),
    ]
