# Generated by Django 5.2.13 on 2026-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_remove_organizationunit_map_organiz_unit_ty_65549f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userassignment',
            name='map_userass_user_id_282861_idx',
        ),
        migrations.RemoveIndex(
            model_name='userassignment',
            name='map_userass_role_id_958ea9_idx',
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='region',
            field=models.CharField(blank=True, choices=[('north', 'منطقة الشمال'), ('center', 'منطقة الوسط'), ('south', 'منطقة الجنوب')], max_length=20, null=True, verbose_name='المنطقة الإقليمية (القاطع/الإسناد)'),
        ),
    ]
