# Generated by Django 5.2.13 on 2026-06-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_remove_userassignment_map_userass_user_id_282861_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'permissions': [('view_global_operations', 'قادر على رؤية كافة عمليات المحافظات (مركزياً)'), ('view_local_operations', 'قادر على رؤية عمليات محافظته فقط (مستوي إقليمي/محلي)')], 'verbose_name': 'مركز العمليات', 'verbose_name_plural': 'مراكز العمليات'},
        ),
    ]
