# Generated by Django 5.2.13 on 2026-06-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_alter_operation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'مركز العمليات', 'verbose_name_plural': 'مراكز العمليات'},
        ),
    ]
