# Generated by Django 5.2.13 on 2026-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_alter_operation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة الإنتاج'),
        ),
    ]
