# Generated by Django 5.2.13 on 2026-06-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_alter_vehicle_production_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=50, verbose_name='رقم المركبة'),
        ),
    ]
