# Generated by Django 5.2.13 on 2026-06-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_alter_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'permissions': [('change_vehicle_status', 'Can change vehicle status')], 'verbose_name': 'مركبة', 'verbose_name_plural': 'المركبات'},
        ),
    ]
