# Generated by Django 5.2.13 on 2026-06-29 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_alter_vehicle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStatusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('read', models.BooleanField(default=False, verbose_name='هل تمت القراءة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستلم')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'إشعار حالة مركبة',
                'verbose_name_plural': 'إشعارات حالات المركبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
