# Generated by Django 5.2.13 on 2026-06-30 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_vehiclestatusnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestatusnotification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='قام بالتغيير'),
        ),
        migrations.AlterField(
            model_name='vehiclestatusnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستلم'),
        ),
    ]
