# Generated by Django 5.2.13 on 2026-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_vehiclestatusnotification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('hq', 'الإدارة العامة'), ('sector', 'قاطع'), ('gov', 'محافظة'), ('directorate', 'مديرية محافظة'), ('dept_branch', 'إدارة داخل مديرية'), ('dept_branch', 'إدارة داخل مركز'), ('center', 'مركز لهدف معين'), ('support_center', 'مركز إسناد')], db_index=True, max_length=30, verbose_name='نوع الوحدة'),
        ),
    ]
