# Generated by Django 5.2.13 on 2026-07-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_alter_organizationunit_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='center',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='governorate',
        ),
    ]
