# Generated by Django 5.2.13 on 2026-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_remove_customuser_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مكان السكن'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(default='', max_length=100, verbose_name='رتبة الموظف'),
            preserve_default=False,
        ),
    ]
