# Generated by Django 5.2.13 on 2026-07-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_alter_employee_address_alter_employee_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'مداوم'), ('leave', 'مجاز')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
