# Generated by Django 5.2.13 on 2026-07-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_dailystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statuses', to='map.employee'),
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الإجازة'),
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='status',
            field=models.CharField(choices=[('present', 'مداوم'), ('leave', 'مجاز'), ('absent', 'غائب')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='مكان السكن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الجوال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رتبة الموظف'),
        ),
    ]
