# Generated by Django 5.2.13 on 2026-07-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_alter_employee_address_alter_employee_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyStatus',
        ),
    ]
