# Generated by Django 5.2.13 on 2026-07-07 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_delete_dailystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('vacation', 'إجازة'), ('mission', 'مهمة رسمية')], default='present', max_length=20, verbose_name='حالة الدوام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='map.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل دوام',
                'verbose_name_plural': 'سجلات الدوام',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
