# Generated by Django 5.2.13 on 2026-07-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_employeeattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='leave_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الإجازة/الغياب'),
        ),
    ]
