# Generated by Django 5.2.13 on 2026-07-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0032_employeeattendance_leave_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('vacation', 'إجازة'), ('mission', 'مهمة رسمية')], default='present', max_length=20, verbose_name='حالة الدوام'),
        ),
    ]
