# Generated by Django 5.2.13 on 2026-07-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_alter_employeeattendance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={},
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='map.employee'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='leave_reason',
            field=models.CharField(blank=True, choices=[('', 'اختر السبب...'), ('sick', 'مرضية'), ('travel', 'سفر'), ('personal', 'ظرف شخصي')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('vacation', 'إجازة'), ('mission', 'مهمة رسمية')], default='present', max_length=20),
        ),
    ]
