# Generated by Django 5.2.13 on 2026-07-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_alter_employeeattendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/', verbose_name='ختم المركز'),
        ),
    ]
