# Generated by Django 5.2.13 on 2026-07-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0035_operation_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='stamp',
        ),
    ]
