# Generated by Django 5.2.13 on 2026-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_remove_operation_seal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='seal_image',
            field=models.ImageField(blank=True, null=True, upload_to='center_seals/', verbose_name='ختم المركز (اختياري)'),
        ),
    ]
