# Generated by Django 5.2.13 on 2026-07-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_operation_seal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='seal_image',
        ),
    ]
