# Generated by Django 5.2.13 on 2026-07-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0040_remove_operation_seal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='operation_stamps/', verbose_name='صورة الختم'),
        ),
    ]
