# Generated by Django 5.2.13 on 2026-07-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_operation_stamp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='overnightshift',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Departure',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='OvernightShift',
        ),
    ]
