# Generated by Django 5.2.13 on 2026-07-13 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0042_remove_leave_employee_remove_overnightshift_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approvals', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_approvals', to='map.operation')),
            ],
            options={
                'unique_together': {('operation', 'date')},
            },
        ),
    ]
