# Generated by Django 5.2.13 on 2026-07-13 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0043_attendanceapproval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceapproval',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendanceapproval',
            name='approval_type',
            field=models.CharField(choices=[('director', 'مدير المديرية'), ('department', 'مدير الإدارة')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendanceapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceapproval',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.operation'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceapproval',
            unique_together={('operation', 'date', 'approval_type')},
        ),
    ]
