# Generated by Django 5.2.13 on 2026-07-21 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0044_alter_attendanceapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by_transport_manager', models.BooleanField(default=False, verbose_name='اعتماد مدير النقل والصيانة')),
                ('transport_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اعتماد النقل والصيانة')),
                ('approved_by_governorate_manager', models.BooleanField(default=False, verbose_name='اعتماد مدير المحافظة')),
                ('governorate_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اعتماد مدير المحافظة')),
                ('governorate_manager_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governorate_approvals', to=settings.AUTH_USER_MODEL, verbose_name='مدير المحافظة المعتَمِد')),
                ('transport_manager_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_approvals', to=settings.AUTH_USER_MODEL, verbose_name='مدير النقل والصيانة المعتَمِد')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='map.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'اعتماد مركبة',
                'verbose_name_plural': 'اعتمادات المركبات',
            },
        ),
    ]
