# Generated by Django 5.2.13 on 2026-07-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0045_vehicleapproval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceapproval',
            options={'permissions': [('can_approve_as_director', 'يمكنه الاعتماد بصلاحية مدير مديرية'), ('can_approve_as_department', 'يمكنه الاعتماد بصلاحية مدير إدارة')]},
        ),
    ]
