# Generated by Django 5.2.13 on 2026-08-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0046_alter_attendanceapproval_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'مداوم'), ('early_leave', 'مغادرة'), ('vacation', 'إجازة'), ('mission', 'مهمة رسمية')], default='present', max_length=20),
        ),
    ]
