# Generated by Django 5.2.13 on 2026-08-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0047_alter_employeeattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='leave_reason',
            field=models.CharField(blank=True, choices=[('', 'اختر السبب...'), ('sick', 'مرض'), ('travel', 'سفر'), ('other', 'غير ذلك')], max_length=20, null=True),
        ),
    ]
