# Generated by Django 5.2.13 on 2026-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0048_alter_employeeattendance_leave_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceapproval',
            options={'ordering': ['-approved_at'], 'permissions': [('can_approve_as_director', 'يمكنه الاعتماد بصلاحية مدير مديرية'), ('can_approve_as_department', 'يمكنه الاعتماد بصلاحية مدير إدارة')]},
        ),
        migrations.AlterUniqueTogether(
            name='attendanceapproval',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendanceapproval',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='اعتماد نشط'),
        ),
        migrations.AddField(
            model_name='attendanceapproval',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
    ]
