# Generated by Django 5.2.13 on 2026-08-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0049_alter_attendanceapproval_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'permissions': [('can_manage_center_attendance', 'يمكنه إدخال وتعديل دوام المركز (مدير مركز / ضابط مناوب)'), ('can_approve_directorate_attendance', 'يمكنه اعتماد دوام المديرية (مدير مديرية / نائب مدير مديرية)')]},
        ),
    ]
