# Generated by Django 5.2.13 on 2026-08-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0050_alter_employeeattendance_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='stamp_image',
        ),
    ]
