# Generated by Django 5.2.13 on 2026-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0051_remove_operation_stamp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='operation_headers/', verbose_name='صورة الترويسة'),
        ),
    ]
