# Generated by Django 5.2.13 on 2026-08-17 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0052_operation_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_updates', to=settings.AUTH_USER_MODEL, verbose_name='آخر من قام بالتعديل'),
        ),
    ]
