# Generated by Django 5.2.13 on 2026-08-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0053_employeeattendance_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendance',
            name='updated_by',
        ),
    ]
