# Generated by Django 5.2.13 on 2026-08-17 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0054_remove_employeeattendance_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تعديل بواسطة'),
        ),
    ]
