# Generated by Django 5.2.13 on 2026-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0055_employeeattendance_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='duty_officer_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الضابط المناوب'),
        ),
    ]
