# Generated by Django 5.2.13 on 2026-08-17 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0056_employeeattendance_duty_officer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'permissions': [('can_manage_center_attendance', 'يمكنه إدخال وتعديل دوام المركز (مدير مركز / ضابط مناوب)'), ('can_approve_directorate_attendance', 'يمكنه اعتماد دوام المديرية (مدير مديرية / نائب مدير المديرية)')]},
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_updates', to=settings.AUTH_USER_MODEL, verbose_name='تعديل بواسطة'),
        ),
    ]
