# Generated by Django 5.2.13 on 2026-08-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0059_attendancenotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceNotification',
        ),
    ]
