# Generated by Django 5.2.13 on 2026-08-23 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0060_delete_attendancenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('notification_type', models.CharField(choices=[('warning', 'تنبيه عدم اعتماد'), ('info', 'معلومات'), ('success', 'اعتماد جديد')], default='warning', max_length=20)),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط التوجيه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإشعار')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار الدوام',
                'verbose_name_plural': 'إشعارات الدوام',
                'ordering': ['-created_at'],
            },
        ),
    ]
