# Generated by Django 5.2.13 on 2026-08-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0061_attendancenotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceNotification',
        ),
    ]
