# Generated by Django 5.2.13 on 2026-08-26 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0065_attendancesystemnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'permissions': [('can_manage_center_attendance', 'يمكنه إدخال وتعديل دوام المركز (مدير مركز / ضابط مناوب)'), ('can_approve_directorate_attendance', 'يمكنه اعتماد دوام المديرية (مدير مديرية / نائب مدير مديرية)')], 'verbose_name': 'سجل دوام موظف', 'verbose_name_plural': 'سجلات دوام الموظفين'},
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='map.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='leave_reason',
            field=models.CharField(blank=True, choices=[('', 'اختر السبب...'), ('sick', 'مرض'), ('travel', 'سفر'), ('other', 'غير ذلك')], default='', max_length=20, null=True, verbose_name='سبب الإجازة/المغادرة'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'مداوم'), ('early_leave', 'مغادرة'), ('vacation', 'إجازة'), ('mission', 'مهمة رسمية')], default='present', max_length=20, verbose_name='حالة الدوام'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
    ]
