# Generated by Django 5.2.13 on 2026-08-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0067_alter_employeeattendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الخبر/الإعلان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(choices=[('weather', 'حالة الطقس'), ('volunteer', 'التطوع'), ('safety', 'السلامة العامة'), ('general', 'عام')], default='general', max_length=20, verbose_name='التصنيف')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='إعلان هام/عاجل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'إعلان / خبر',
                'verbose_name_plural': 'الإعلانات والأخبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='تنبيه عاجل', max_length=100, verbose_name='عنوان التنبيه')),
                ('content', models.TextField(verbose_name='محتوى التنبيه')),
                ('emergency_number', models.CharField(default='102', max_length=20, verbose_name='رقم الطوارئ')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل التنبيه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'تنبيه عاجل',
                'verbose_name_plural': 'التنبيهات العاجلة',
                'ordering': ['-created_at'],
            },
        ),
    ]
