# Generated by Django 5.2.13 on 2026-08-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0068_announcement_emergencyticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level'], 'permissions': [('can_approve_directorate_attendance', 'Can approve directorate attendance')], 'verbose_name': 'دور', 'verbose_name_plural': '2- الأدوار'},
        ),
    ]
