# Generated by Django 5.2.17 on 2026-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0069_alter_role_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='work_type',
            field=models.CharField(choices=[('fire', 'إطفاء'), ('rescue', 'إنقاذ'), ('fire_and_rescue', 'إطفاء وإنقاذ'), ('services', 'خدمات'), ('tank', 'تنك تزويد')], max_length=20, verbose_name='نوع المهمة'),
        ),
    ]
