# Generated by Django 5.2.17 on 2026-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0070_alter_vehicle_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, choices=[('soldier', 'جندي'), ('corporal', 'عريف'), ('sergeant', 'رقيب'), ('first_sergeant', 'رقيب أول'), ('warrant', 'مساعد'), ('first_warrant', 'مساعد أول'), ('lieutenant', 'ملازم'), ('first_lieutenant', 'ملازم أول'), ('captain', 'نقيب'), ('major', 'رائد'), ('lt_colonel', 'مقدم'), ('colonel', 'عقيد'), ('brigadier', 'عميد'), ('major_general', 'لواء')], default='', max_length=20, verbose_name='الرتبة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unique_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم الوظيفي'),
        ),
    ]
