# Generated by Django 5.2.17 on 2026-09-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0071_customuser_rank_customuser_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, choices=[('soldier', 'الجندي'), ('corporal', 'العريف'), ('sergeant', 'الرقيب'), ('first_sergeant', 'الرقيب أول'), ('warrant', 'المساعد'), ('first_warrant', 'المساعد أول'), ('lieutenant', 'الملازم'), ('first_lieutenant', 'الملازم أول'), ('captain', 'النقيب'), ('major', 'الرائد'), ('lt_colonel', 'المقدم'), ('colonel', 'العقيد'), ('brigadier', 'العميد'), ('major_general', 'اللواء')], default='', max_length=20, verbose_name='الرتبة'),
        ),
    ]
